on: [pull-request]

name: mabl

jobs:
  test:
    name: Mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run mabl tests against deployment
        id: mabl-test-deployment
        uses: ./
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
        with:
          application-id: l-j3VqIO6lLLOOEoFTPSxA-a
          environment-id: rtb4kWD5LuTr2KxaHvwfaA-e
        continue-on-error: true
      - name: Do something on failure
        run: echo 'too many failures.  Do something.'
        if: ({{steps.mabl-test-deployment.journey_failures}} > 1)
